# Generated by Django 3.1.1 on 2020-09-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('other', models.CharField(max_length=255, null=True)),
                ('dob', models.CharField(max_length=255, null=True)),
                ('degree', models.CharField(max_length=6655, null=True)),
                ('resume', models.FileField(upload_to='documents/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.BooleanField(default=False)),
                ('comp_start_year', models.CharField(max_length=255, null=True)),
                ('comp_start_month', models.CharField(max_length=255, null=True)),
                ('comp_end_year', models.CharField(max_length=255, null=True)),
                ('comp_end_month', models.CharField(max_length=255, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=6655, null=True)),
                ('college_start_year', models.CharField(max_length=255, null=True)),
                ('college_start_month', models.CharField(max_length=255, null=True)),
                ('college_end_year', models.CharField(max_length=255, null=True)),
                ('college_end_month', models.CharField(max_length=255, null=True)),
                ('currently_pursuing', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
            ],
        ),
    ]
