# Generated by Django 3.1.1 on 2020-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='degree',
        ),
        migrations.AddField(
            model_name='employeeeducationdetail',
            name='degree',
            field=models.CharField(max_length=6655, null=True),
        ),
    ]
