# Generated by Django 3.1.1 on 2020-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200923_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkdetail',
            name='company_name',
            field=models.CharField(max_length=6000, null=True),
        ),
    ]
